filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log

    multiline.pattern: '^\['
    multiline.negate: true
    multiline.match: after
    
#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]

output.logstash:
  hosts: ["logstash:5044"]